# Generated by Django 3.0.4 on 2020-03-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='Question Title', max_length=200),
        ),
    ]
